name: Link PDR PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  link-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Link PDR PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUBMODULE_REPO: ${{ github.repository }}
          PDR_REPO: "tangophi/parent_repo" # Replace with the actual parent repo
        run: |
          # Function to get PRs from a repo by branch name
          get_pr_url() {
            repo=$1
            branch=$2
            pr_url=$(gh pr list -R "$repo" --head "$branch" --json url -q '.[0].url')
            echo "$pr_url"
          }

          # Function to update PR description
          update_pr_description() {
            pr_number=$1
            pr_body=$2
            new_link=$3
            existing_links=$(echo "$pr_body" | grep -o "https://github.com/.*")
            
            if ! echo "$existing_links" | grep -q "$new_link"; then
              new_body="$pr_body\n\n**Related PRs:**\n$new_link"
              gh pr edit "$pr_number" -R "$SUBMODULE_REPO" --body "$new_body"
            fi
          }

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            pr_number=${{ github.event.pull_request.number }}
            pr_body="${{ github.event.pull_request.body }}"
            branch=${{ github.event.pull_request.head.ref }}
            
            pdr_pr_url=$(get_pr_url "$PDR_REPO" "$branch")
            
            if [ -n "$pdr_pr_url" ]; then
              update_pr_description "$pr_number" "$pr_body" "$pdr_pr_url"
            fi
          else # schedule
            prs=$(gh pr list -R "$SUBMODULE_REPO" --json number,body,headRefName)
            echo "$prs" | while IFS= read -r pr; do
              pr_number=$(echo "$pr" | jq -r '.number')
              pr_body=$(echo "$pr" | jq -r '.body')
              branch=$(echo "$pr" | jq -r '.headRefName')

              pdr_pr_url=$(get_pr_url "$PDR_REPO" "$branch")

              if [ -n "$pdr_pr_url" ]; then
                update_pr_description "$pr_number" "$pr_body" "$pdr_pr_url"
              fi
            done
          fi
