name: Link PDR PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  link-to-pdr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Extract branch name
        id: branch
        run: echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT

      - name: Link to matching PDR PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = "${{ steps.branch.outputs.branch_name }}";
            const subPR = context.payload.pull_request;

            // Find matching PDR PR
            const { data: prs } = await github.pulls.list({
              owner: "tangophi",
              repo: "parent_repo", // PDR repo
              state: "open",
              head: `tangophi:${branch}`
            });

            if (prs.length > 0) {
              const pdrPR = prs[0];

              // Update submodule PR with link to PDR
              const pdrLinkLine = `Linked PDR PR: [parent_repo#${pdrPR.number}](${pdrPR.html_url})`;
              const newSubBody = (subPR.body || "") + "\n" + pdrLinkLine;
              await github.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: subPR.number,
                body: newSubBody
              });

              // Update PDR PR with link to submodule
              const subLinkLine = `Linked Submodule PR: [${context.repo.repo}#${subPR.number}](${subPR.html_url})`;
              const newPdrBody = (pdrPR.body || "") + "\n" + subLinkLine;
              await github.pulls.update({
                owner: "tangophi",
                repo: "parent_repo",
                pull_number: pdrPR.number,
                body: newPdrBody
              });
            }
